// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LoroDoc>>
abstract class LoroDoc implements RustOpaqueInterface {
  /// Commit current transaction
  Future<void> commit();

  /// Export document as update bytes
  Future<Uint8List> export_();

  /// Export document as snapshot bytes (compatibility method)
  Future<Uint8List> exportSnapshot();

  /// Get a list container by name
  Future<LoroList> getList({required String name});

  /// Get a map container by name
  Future<LoroMap> getMap({required String name});

  /// Get a text container by name
  Future<LoroText> getText({required String name});

  /// Import updates from bytes
  Future<void> import_({required List<int> bytes});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new Loro document
  static Future<LoroDoc> newInstance() =>
      RustLib.instance.api.crateApiLoroDocNew();

  /// Get the peer ID of this document
  Future<BigInt> peerId();

  /// Set the peer ID
  Future<void> setPeerId({required BigInt peer});

  /// Get the JSON representation of the document
  Future<String> toJson();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LoroList>>
abstract class LoroList implements RustOpaqueInterface {
  /// Delete item at position
  Future<void> delete({required int pos, required int len});

  /// Get value at index as JSON string
  Future<String?> getJson({required int index});

  /// Insert a string value at position
  Future<void> insertString({required int pos, required String value});

  /// Check if list is empty
  Future<bool> isEmpty();

  /// Get the length of the list
  Future<int> len();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LoroMap>>
abstract class LoroMap implements RustOpaqueInterface {
  /// Delete a key from the map
  Future<void> delete({required String key});

  /// Get value by key as JSON string
  Future<String?> getJson({required String key});

  /// Insert a string value with key
  Future<void> insertString({required String key, required String value});

  /// Check if map is empty
  Future<bool> isEmpty();

  /// Get all keys
  Future<List<String>> keys();

  /// Get the size of the map
  Future<int> len();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LoroText>>
abstract class LoroText implements RustOpaqueInterface {
  /// Delete text at position
  Future<void> delete({required int pos, required int len});

  /// Insert text at position
  Future<void> insert({required int pos, required String text});

  /// Check if text is empty
  Future<bool> isEmpty();

  /// Get the length of the text
  Future<int> len();

  /// Get the text content as string
  Future<String> text();
}
