// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LoroDocPtr => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LoroListPtr => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LoroMapPtr => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LoroTextPtr => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText;



                  @protected LoroDoc dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(dynamic raw);

@protected LoroList dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(dynamic raw);

@protected LoroMap dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(dynamic raw);

@protected LoroText dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(dynamic raw);

@protected LoroDoc dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(dynamic raw);

@protected LoroList dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(dynamic raw);

@protected LoroMap dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(dynamic raw);

@protected LoroText dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(dynamic raw);

@protected LoroDoc dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(dynamic raw);

@protected LoroList dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(dynamic raw);

@protected LoroMap dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(dynamic raw);

@protected LoroText dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected List<String> dco_decode_list_String(dynamic raw);

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected BigInt dco_decode_u_64(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected BigInt dco_decode_usize(dynamic raw);

@protected LoroDoc sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(SseDeserializer deserializer);

@protected LoroList sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(SseDeserializer deserializer);

@protected LoroMap sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(SseDeserializer deserializer);

@protected LoroText sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(SseDeserializer deserializer);

@protected LoroDoc sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(SseDeserializer deserializer);

@protected LoroList sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(SseDeserializer deserializer);

@protected LoroMap sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(SseDeserializer deserializer);

@protected LoroText sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(SseDeserializer deserializer);

@protected LoroDoc sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(SseDeserializer deserializer);

@protected LoroList sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(SseDeserializer deserializer);

@protected LoroMap sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(SseDeserializer deserializer);

@protected LoroText sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected List<String> sse_decode_list_String(SseDeserializer deserializer);

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected BigInt sse_decode_usize(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(LoroDoc self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(LoroList self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(LoroMap self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(LoroText self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(LoroDoc self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(LoroList self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(LoroMap self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(LoroText self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(LoroDoc self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(LoroList self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(LoroMap self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(LoroText self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_usize(BigInt self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);
                }
                


// Section: wire_class

class RustLibWire implements BaseWire {
            RustLibWire.fromExternalLibrary(ExternalLibrary lib);

            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(ptr);

void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(ptr);

void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(ptr);

void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(ptr);

void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(ptr);

void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(ptr);

void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(ptr);

void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(ptr);
        }
        @JS('wasm_bindgen') external RustLibWasmModule get wasmModule;

        @JS() @anonymous extension type RustLibWasmModule._(JSObject _) implements JSObject {
            external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(int ptr);

external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(int ptr);

external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(int ptr);

external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(int ptr);

external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(int ptr);

external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(int ptr);

external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(int ptr);

external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(int ptr);
        }
        