// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 96556466;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'loro_dart',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiLoroDocCommit({required LoroDoc that});

  Future<Uint8List> crateApiLoroDocExport({required LoroDoc that});

  Future<Uint8List> crateApiLoroDocExportSnapshot({required LoroDoc that});

  Future<LoroList> crateApiLoroDocGetList(
      {required LoroDoc that, required String name});

  Future<LoroMap> crateApiLoroDocGetMap(
      {required LoroDoc that, required String name});

  Future<LoroText> crateApiLoroDocGetText(
      {required LoroDoc that, required String name});

  Future<void> crateApiLoroDocImport(
      {required LoroDoc that, required List<int> bytes});

  Future<LoroDoc> crateApiLoroDocNew();

  Future<BigInt> crateApiLoroDocPeerId({required LoroDoc that});

  Future<void> crateApiLoroDocSetPeerId(
      {required LoroDoc that, required BigInt peer});

  Future<String> crateApiLoroDocToJson({required LoroDoc that});

  Future<void> crateApiLoroListDelete(
      {required LoroList that, required int pos, required int len});

  Future<String?> crateApiLoroListGetJson(
      {required LoroList that, required int index});

  Future<void> crateApiLoroListInsertString(
      {required LoroList that, required int pos, required String value});

  Future<bool> crateApiLoroListIsEmpty({required LoroList that});

  Future<int> crateApiLoroListLen({required LoroList that});

  Future<void> crateApiLoroMapDelete(
      {required LoroMap that, required String key});

  Future<String?> crateApiLoroMapGetJson(
      {required LoroMap that, required String key});

  Future<void> crateApiLoroMapInsertString(
      {required LoroMap that, required String key, required String value});

  Future<bool> crateApiLoroMapIsEmpty({required LoroMap that});

  Future<List<String>> crateApiLoroMapKeys({required LoroMap that});

  Future<int> crateApiLoroMapLen({required LoroMap that});

  Future<void> crateApiLoroTextDelete(
      {required LoroText that, required int pos, required int len});

  Future<void> crateApiLoroTextInsert(
      {required LoroText that, required int pos, required String text});

  Future<bool> crateApiLoroTextIsEmpty({required LoroText that});

  Future<int> crateApiLoroTextLen({required LoroText that});

  Future<String> crateApiLoroTextText({required LoroText that});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_LoroDoc;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_LoroDoc;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LoroDocPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_LoroList;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_LoroList;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LoroListPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_LoroMap;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_LoroMap;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LoroMapPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_LoroText;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_LoroText;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LoroTextPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiLoroDocCommit({required LoroDoc that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroDocCommitConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocCommitConstMeta => const TaskConstMeta(
        debugName: "LoroDoc_commit",
        argNames: ["that"],
      );

  @override
  Future<Uint8List> crateApiLoroDocExport({required LoroDoc that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoroDocExportConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocExportConstMeta => const TaskConstMeta(
        debugName: "LoroDoc_export",
        argNames: ["that"],
      );

  @override
  Future<Uint8List> crateApiLoroDocExportSnapshot({required LoroDoc that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoroDocExportSnapshotConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocExportSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "LoroDoc_export_snapshot",
        argNames: ["that"],
      );

  @override
  Future<LoroList> crateApiLoroDocGetList(
      {required LoroDoc that, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
            that, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroDocGetListConstMeta,
      argValues: [that, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocGetListConstMeta => const TaskConstMeta(
        debugName: "LoroDoc_get_list",
        argNames: ["that", "name"],
      );

  @override
  Future<LoroMap> crateApiLoroDocGetMap(
      {required LoroDoc that, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
            that, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroDocGetMapConstMeta,
      argValues: [that, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocGetMapConstMeta => const TaskConstMeta(
        debugName: "LoroDoc_get_map",
        argNames: ["that", "name"],
      );

  @override
  Future<LoroText> crateApiLoroDocGetText(
      {required LoroDoc that, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
            that, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroDocGetTextConstMeta,
      argValues: [that, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocGetTextConstMeta => const TaskConstMeta(
        debugName: "LoroDoc_get_text",
        argNames: ["that", "name"],
      );

  @override
  Future<void> crateApiLoroDocImport(
      {required LoroDoc that, required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
            that, serializer);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoroDocImportConstMeta,
      argValues: [that, bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocImportConstMeta => const TaskConstMeta(
        debugName: "LoroDoc_import",
        argNames: ["that", "bytes"],
      );

  @override
  Future<LoroDoc> crateApiLoroDocNew() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroDocNewConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocNewConstMeta => const TaskConstMeta(
        debugName: "LoroDoc_new",
        argNames: [],
      );

  @override
  Future<BigInt> crateApiLoroDocPeerId({required LoroDoc that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroDocPeerIdConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocPeerIdConstMeta => const TaskConstMeta(
        debugName: "LoroDoc_peer_id",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiLoroDocSetPeerId(
      {required LoroDoc that, required BigInt peer}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
            that, serializer);
        sse_encode_u_64(peer, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoroDocSetPeerIdConstMeta,
      argValues: [that, peer],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocSetPeerIdConstMeta => const TaskConstMeta(
        debugName: "LoroDoc_set_peer_id",
        argNames: ["that", "peer"],
      );

  @override
  Future<String> crateApiLoroDocToJson({required LoroDoc that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroDocToJsonConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroDocToJsonConstMeta => const TaskConstMeta(
        debugName: "LoroDoc_to_json",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiLoroListDelete(
      {required LoroList that, required int pos, required int len}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
            that, serializer);
        sse_encode_u_32(pos, serializer);
        sse_encode_u_32(len, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoroListDeleteConstMeta,
      argValues: [that, pos, len],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroListDeleteConstMeta => const TaskConstMeta(
        debugName: "LoroList_delete",
        argNames: ["that", "pos", "len"],
      );

  @override
  Future<String?> crateApiLoroListGetJson(
      {required LoroList that, required int index}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
            that, serializer);
        sse_encode_u_32(index, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroListGetJsonConstMeta,
      argValues: [that, index],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroListGetJsonConstMeta => const TaskConstMeta(
        debugName: "LoroList_get_json",
        argNames: ["that", "index"],
      );

  @override
  Future<void> crateApiLoroListInsertString(
      {required LoroList that, required int pos, required String value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
            that, serializer);
        sse_encode_u_32(pos, serializer);
        sse_encode_String(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoroListInsertStringConstMeta,
      argValues: [that, pos, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroListInsertStringConstMeta =>
      const TaskConstMeta(
        debugName: "LoroList_insert_string",
        argNames: ["that", "pos", "value"],
      );

  @override
  Future<bool> crateApiLoroListIsEmpty({required LoroList that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroListIsEmptyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroListIsEmptyConstMeta => const TaskConstMeta(
        debugName: "LoroList_is_empty",
        argNames: ["that"],
      );

  @override
  Future<int> crateApiLoroListLen({required LoroList that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroListLenConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroListLenConstMeta => const TaskConstMeta(
        debugName: "LoroList_len",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiLoroMapDelete(
      {required LoroMap that, required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
            that, serializer);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoroMapDeleteConstMeta,
      argValues: [that, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroMapDeleteConstMeta => const TaskConstMeta(
        debugName: "LoroMap_delete",
        argNames: ["that", "key"],
      );

  @override
  Future<String?> crateApiLoroMapGetJson(
      {required LoroMap that, required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
            that, serializer);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroMapGetJsonConstMeta,
      argValues: [that, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroMapGetJsonConstMeta => const TaskConstMeta(
        debugName: "LoroMap_get_json",
        argNames: ["that", "key"],
      );

  @override
  Future<void> crateApiLoroMapInsertString(
      {required LoroMap that, required String key, required String value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
            that, serializer);
        sse_encode_String(key, serializer);
        sse_encode_String(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoroMapInsertStringConstMeta,
      argValues: [that, key, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroMapInsertStringConstMeta =>
      const TaskConstMeta(
        debugName: "LoroMap_insert_string",
        argNames: ["that", "key", "value"],
      );

  @override
  Future<bool> crateApiLoroMapIsEmpty({required LoroMap that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroMapIsEmptyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroMapIsEmptyConstMeta => const TaskConstMeta(
        debugName: "LoroMap_is_empty",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateApiLoroMapKeys({required LoroMap that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroMapKeysConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroMapKeysConstMeta => const TaskConstMeta(
        debugName: "LoroMap_keys",
        argNames: ["that"],
      );

  @override
  Future<int> crateApiLoroMapLen({required LoroMap that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroMapLenConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroMapLenConstMeta => const TaskConstMeta(
        debugName: "LoroMap_len",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiLoroTextDelete(
      {required LoroText that, required int pos, required int len}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
            that, serializer);
        sse_encode_u_32(pos, serializer);
        sse_encode_u_32(len, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoroTextDeleteConstMeta,
      argValues: [that, pos, len],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroTextDeleteConstMeta => const TaskConstMeta(
        debugName: "LoroText_delete",
        argNames: ["that", "pos", "len"],
      );

  @override
  Future<void> crateApiLoroTextInsert(
      {required LoroText that, required int pos, required String text}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
            that, serializer);
        sse_encode_u_32(pos, serializer);
        sse_encode_String(text, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoroTextInsertConstMeta,
      argValues: [that, pos, text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroTextInsertConstMeta => const TaskConstMeta(
        debugName: "LoroText_insert",
        argNames: ["that", "pos", "text"],
      );

  @override
  Future<bool> crateApiLoroTextIsEmpty({required LoroText that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroTextIsEmptyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroTextIsEmptyConstMeta => const TaskConstMeta(
        debugName: "LoroText_is_empty",
        argNames: ["that"],
      );

  @override
  Future<int> crateApiLoroTextLen({required LoroText that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroTextLenConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroTextLenConstMeta => const TaskConstMeta(
        debugName: "LoroText_len",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiLoroTextText({required LoroText that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLoroTextTextConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoroTextTextConstMeta => const TaskConstMeta(
        debugName: "LoroText_text",
        argNames: ["that"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_LoroDoc => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_LoroDoc => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_LoroList => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_LoroList => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_LoroMap => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_LoroMap => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_LoroText => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_LoroText => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText;

  @protected
  LoroDoc
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroDocImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroList
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroListImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroMap
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroMapImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroText
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroTextImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroDoc
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroDocImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroList
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroListImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroMap
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroMapImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroText
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroTextImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroDoc
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroDocImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroList
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroListImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroMap
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroMapImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoroText
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoroTextImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  LoroDoc
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroDocImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroList
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroListImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroMap
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroMapImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroText
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroTextImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroDoc
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroDocImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroList
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroListImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroMap
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroMapImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroText
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroTextImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroDoc
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroDocImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroList
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroListImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroMap
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroMapImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LoroText
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoroTextImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
          LoroDoc self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroDocImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
          LoroList self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroListImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
          LoroMap self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroMapImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
          LoroText self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroTextImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
          LoroDoc self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroDocImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
          LoroList self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroListImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
          LoroMap self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroMapImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
          LoroText self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroTextImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroDoc(
          LoroDoc self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroDocImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroList(
          LoroList self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroListImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroMap(
          LoroMap self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroMapImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoroText(
          LoroText self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LoroTextImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class LoroDocImpl extends RustOpaque implements LoroDoc {
  // Not to be used by end users
  LoroDocImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LoroDocImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LoroDoc,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LoroDoc,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LoroDocPtr,
  );

  /// Commit current transaction
  Future<void> commit() => RustLib.instance.api.crateApiLoroDocCommit(
        that: this,
      );

  /// Export document as update bytes
  Future<Uint8List> export_() => RustLib.instance.api.crateApiLoroDocExport(
        that: this,
      );

  /// Export document as snapshot bytes (compatibility method)
  Future<Uint8List> exportSnapshot() =>
      RustLib.instance.api.crateApiLoroDocExportSnapshot(
        that: this,
      );

  /// Get a list container by name
  Future<LoroList> getList({required String name}) =>
      RustLib.instance.api.crateApiLoroDocGetList(that: this, name: name);

  /// Get a map container by name
  Future<LoroMap> getMap({required String name}) =>
      RustLib.instance.api.crateApiLoroDocGetMap(that: this, name: name);

  /// Get a text container by name
  Future<LoroText> getText({required String name}) =>
      RustLib.instance.api.crateApiLoroDocGetText(that: this, name: name);

  /// Import updates from bytes
  Future<void> import_({required List<int> bytes}) =>
      RustLib.instance.api.crateApiLoroDocImport(that: this, bytes: bytes);

  /// Get the peer ID of this document
  Future<BigInt> peerId() => RustLib.instance.api.crateApiLoroDocPeerId(
        that: this,
      );

  /// Set the peer ID
  Future<void> setPeerId({required BigInt peer}) =>
      RustLib.instance.api.crateApiLoroDocSetPeerId(that: this, peer: peer);

  /// Get the JSON representation of the document
  Future<String> toJson() => RustLib.instance.api.crateApiLoroDocToJson(
        that: this,
      );
}

@sealed
class LoroListImpl extends RustOpaque implements LoroList {
  // Not to be used by end users
  LoroListImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LoroListImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LoroList,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LoroList,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LoroListPtr,
  );

  /// Delete item at position
  Future<void> delete({required int pos, required int len}) =>
      RustLib.instance.api
          .crateApiLoroListDelete(that: this, pos: pos, len: len);

  /// Get value at index as JSON string
  Future<String?> getJson({required int index}) =>
      RustLib.instance.api.crateApiLoroListGetJson(that: this, index: index);

  /// Insert a string value at position
  Future<void> insertString({required int pos, required String value}) =>
      RustLib.instance.api
          .crateApiLoroListInsertString(that: this, pos: pos, value: value);

  /// Check if list is empty
  Future<bool> isEmpty() => RustLib.instance.api.crateApiLoroListIsEmpty(
        that: this,
      );

  /// Get the length of the list
  Future<int> len() => RustLib.instance.api.crateApiLoroListLen(
        that: this,
      );
}

@sealed
class LoroMapImpl extends RustOpaque implements LoroMap {
  // Not to be used by end users
  LoroMapImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LoroMapImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LoroMap,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LoroMap,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LoroMapPtr,
  );

  /// Delete a key from the map
  Future<void> delete({required String key}) =>
      RustLib.instance.api.crateApiLoroMapDelete(that: this, key: key);

  /// Get value by key as JSON string
  Future<String?> getJson({required String key}) =>
      RustLib.instance.api.crateApiLoroMapGetJson(that: this, key: key);

  /// Insert a string value with key
  Future<void> insertString({required String key, required String value}) =>
      RustLib.instance.api
          .crateApiLoroMapInsertString(that: this, key: key, value: value);

  /// Check if map is empty
  Future<bool> isEmpty() => RustLib.instance.api.crateApiLoroMapIsEmpty(
        that: this,
      );

  /// Get all keys
  Future<List<String>> keys() => RustLib.instance.api.crateApiLoroMapKeys(
        that: this,
      );

  /// Get the size of the map
  Future<int> len() => RustLib.instance.api.crateApiLoroMapLen(
        that: this,
      );
}

@sealed
class LoroTextImpl extends RustOpaque implements LoroText {
  // Not to be used by end users
  LoroTextImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LoroTextImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LoroText,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LoroText,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LoroTextPtr,
  );

  /// Delete text at position
  Future<void> delete({required int pos, required int len}) =>
      RustLib.instance.api
          .crateApiLoroTextDelete(that: this, pos: pos, len: len);

  /// Insert text at position
  Future<void> insert({required int pos, required String text}) =>
      RustLib.instance.api
          .crateApiLoroTextInsert(that: this, pos: pos, text: text);

  /// Check if text is empty
  Future<bool> isEmpty() => RustLib.instance.api.crateApiLoroTextIsEmpty(
        that: this,
      );

  /// Get the length of the text
  Future<int> len() => RustLib.instance.api.crateApiLoroTextLen(
        that: this,
      );

  /// Get the text content as string
  Future<String> text() => RustLib.instance.api.crateApiLoroTextText(
        that: this,
      );
}
